version: '3'

services:
  nginx:
    image: nginx:1.23.0
    container_name: webserver
    depends_on:
        - db
        - wordpress
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/ssl/
    links:
      - wordpress

  wordpress:
    ports: []






