version: '3'

services:
  nginx:
    image: nginx:1.23.0
    container_name: webserver
    depends_on:
        - db
        - wordpress
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl/

  wordpress:
      ports: []



